- name: Install Firewalld
  package:
    name: "firewalld"
  when: ansible_os_family in ["RedHat", "Suse"]

- name: Install SELinux Python Library
  package: 
    name: "libselinux-python3"
  when: ansible_os_family in ["RedHat"]

- name: Install UFW 
  package:
    name: "ufw"
  when: ansible_os_family in ["Debian"]

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  when: ansible_os_family in ["RedHat"]

- name: Remove Default SSH Rule Firewalld
  ansible.posix.firewalld:
    service: ssh
    permanent: no
    state: disabled
  when: ansible_os_family in ["RedHat", "Suse"]

- name: Remove Default SSH Rule UFW
  community.general.ufw:
    rule: allow
    name: OpenSSH
    delete: yes
  when: ansible_os_family in ["Debian"]

- name: Deploy SSH Rule Firewalld
  ansible.posix.firewalld:
    port: "{{ SSH_PORT }}/tcp"
    permanent: yes
    state: enabled
  when: ansible_os_family in ["RedHat", "Suse"]

- name: Deploy SSH Rule UFW
  community.general.ufw:
    rule: allow
    port: "{{ SSH_PORT }}"
    proto: tcp
  when: ansible_os_family in ["Debian"]

- name: Custom Firewall Rules Firewalld
  ansible.posix.firewalld:
    permanent: yes
    port: "{{ item.value.port }}/{{ item.value.proto }}"
    state: enabled
  when:
    - CUSTOM_FIREWALL_RULES is defined
    - CUSTOM_FIREWALL_RULES | length > 0
    - ansible_os_family in ["RedHat", "Suse"]
  with_dict: "{{ CUSTOM_FIREWALL_RULES }}"
  notify: firewalld_restart

- name: Custom Firewall Rules UFW
  community.general.ufw:
    rule: allow
    port: "{{ item.value.port }}"
    proto: "{{ item.value.proto }}"
  when:
    - CUSTOM_FIREWALL_RULES is defined
    - CUSTOM_FIREWALL_RULES | length > 0
    - ansible_os_family in ["Debian"]
  with_dict: "{{ CUSTOM_FIREWALL_RULES }}"
    

- name: Default Policy UFW
  community.general.ufw:
    state: enabled
    policy: reject
  when: ansible_os_family in ["Debian"]
  notify: ufw_restart
