- name: ssh_restart
  service:
    name: sshd
    state: restarted
    enabled: yes

- name: firewalld_restart
  service:
    name: firewalld
    state: restarted
    enabled: yes
  

- name: ufw_restart
  service:
    name: ufw
    state: restarted
    enabled: yes
